version: '3'

services:
  sharex-api:
    image: sharex-api:local
    container_name: sharex-api
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - 8000:80
    volumes:
      - ./i:/var/www/html/i
