version: '3'

services:
  share-x-api:
    image: share-x-api:local
    container_name: share-x-api
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - 8000:80
    volumes:
      - ./files:/var/www/html/files
