name: Docker Image CI

on:
  push:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Login to DockerHub Registry
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
      - name: Build the latest Docker image
        run: docker build . --file Dockerfile --tag nathanstrobbe/sharex-api:latest
      - name: Push the latest Docker image
        run: docker push nathanstrobbe/sharex-api:latest
